version: '2.1'
services:
  kibana:
    image: kibana:5.1.2
    hostname: kibana
    container_name: kibana 
    restart: always
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
      - SERVER_NAME=localhost
    external_links:
      - elasticsearch:elasticsearch
