services:
  kafka_manager:
    image: hlebalbau/kafka-manager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "192.168.99.100:2181/kafka"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null