version: '2.1'
services:
  kafka_manager:
    image: hlebalbau/kafka-manager
    hostname: kafka-manager
    container_name: kafka-manager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "hbase-docker:2181/kafka"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null